### PR TITLE
 ✨ add checks for the mongodb in the user data namespace

### PR DESCRIPTION
**Pull request by wei-lee**
# JIRA

https://issues.jboss.org/browse/RHMAP-21515

### CODE REVIEW

**Comment by wei-lee** [comment]
@pmccarthy @jessesarn can you please review this and perhaps test it somewhere? I will try it in the csteam2 cluster and I will expect the checks to fail. Would be good to verify it in a cluster where the checks will pass.

**Comment by jessesarn** [comment]
I'll update the nagios on rhm-eng-a for rhmap-core to use this image version and let you know.

**Comment by Nanyte25** [comment]
I am checking it on rhm-eng-a aswell @jessesarn and @wei-lee

**Comment by jessesarn** [comment]
One other problem while I'm still looking at why the parameter didn't get through.  We need to add userdata or some similar string to the check names.  Right now, the mongodb-<1,2,3>::Ping checks get the same name as the system mongos so there ends up only being 3 checks instead of 6.

On the bright side, the 3 userdata mongo pings overwrote the system ones and are the ones actually getting tested and passing right now.

**Pull request closed without merging**
