### PR TITLE
Base valid digger checks on env var

### PR DESCRIPTION
**Pull request by PhilipGough**
ping @laurafitzgerald

### CODE REVIEW

**Comment by matskiv** [comment]
:eyes:

**Comment by laurafitzgerald** [comment]
**Verfication**
Verified that ios and android checks run only when they are listed in PLATFORMS

**Comment by laurafitzgerald** [comment]
Merging and cherry-picking to release branch

**Comment by laurafitzgerald** [comment]
Also pushed dev image to aerogear.org

**Pull request merged**
