### PR TITLE
mysql service list

### PR DESCRIPTION
**Pull request by odra**
Uses a list o generate mysql nagios checks for all hosts

### CODE REVIEW

**Comment by odra** [comment]
@jessesarn I noticed we are always adding the userspace mongodb checks: https://github.com/feedhenry/nagios-container/blob/4a49e091812b34084e90db3787a42dbb533977a1/make-nagios-fhservices-cfg#L41 - should we add some kind of check to not include those if the running rhmap instance did not deploy the userpace parts?

**Comment by jessesarn** [comment]
@odra Yes, I think we should avoid adding hosted-specific checks to self-managed installs.

**Comment by odra** [comment]
Ok, I will create another jira ticket to fix the userspace mongodb check to keep the pr clean

**Comment by jessesarn** [comment]
@odra cool thx

**Pull request merged**
